-- CreateTable
CREATE TABLE `user_permissions` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` INTEGER NOT NULL,
    `permission` ENUM('PRODUCTS_WRITE', 'PRODUCTS_DELETE', 'INVENTORY_WRITE', 'SALES_VOID', 'SALES_HISTORY', 'TRANSFERS_APPROVE', 'EMPLOYEES_VIEW', 'EMPLOYEES_WRITE', 'ACCOUNTING_VIEW', 'ACCOUNTING_WRITE', 'REPORTS_VIEW', 'USERS_MANAGE', 'SETTINGS_MANAGE', 'AUDIT_VIEW', 'CUSTOMERS_WRITE', 'SUPPLIERS_WRITE', 'DOCUMENTS_WRITE', 'PURCHASES_MANAGE') NOT NULL,
    `granted` BOOLEAN NOT NULL DEFAULT true,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `user_permissions_user_id_permission_key`(`user_id`, `permission`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `user_permissions` ADD CONSTRAINT `user_permissions_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
